# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check links of the dataset

on:
  schedule:
    # run at 1:00 UTC (10:00 JST) on the first day of each month
    - cron: "00 10 1 * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pandas tqdm requests
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check if the links of the images in dataset are valid
      run: |
        python tests/check_dataset.py
